import React from 'react';
import Head from 'next/head';
import Catalog from '../components/Catalog';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Catalog />
    </div>
  )
}
